apiVersion: external-secrets.io/v1
kind: SecretStore # SecretStore is a cluster-scoped resource that defines how to connect to an external secret management system, such as HashiCorp Vault, AWS Secrets Manager, or Azure Key Vault.
# It allows you to configure the connection details and authentication methods for accessing secrets from the external system.
metadata:
  name: vault-backend
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.Local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: v1
kind: Secret # This secret is used to store the Vault token for authentication with the Vault server.
metadata:
  name: vault-token
  namespace: vault
stringData: # The token is stored as a string in the secret's data. In a production environment, you would typically use a more secure method to manage and rotate the token.
  token: root